"""Init migration version: 1.0.3

Revision ID: 8ad00a0037ec
Revises: 
Create Date: 2025-10-21 17:25:31.304061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ad00a0037ec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_main',
    sa.Column('id_admin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_admin')
    )
    op.create_table('agente_virtual',
    sa.Column('id_agenVitual', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_agent', sa.String(length=60), nullable=False),
    sa.Column('level_access', sa.String(length=60), nullable=False),
    sa.Column('status_agent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id_agenVitual'),
    sa.UniqueConstraint('level_access'),
    sa.UniqueConstraint('type_agent')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nameuser', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_activate', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nameuser')
    )
    op.create_table('video',
    sa.Column('id_video', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title_video', sa.String(length=60), nullable=False),
    sa.Column('description_video', sa.String(length=255), nullable=True),
    sa.Column('publication_date_video', sa.Date(), nullable=False),
    sa.Column('miniatura_video', sa.String(length=255), nullable=False),
    sa.Column('like_video', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_video'),
    sa.UniqueConstraint('like_video'),
    sa.UniqueConstraint('miniatura_video'),
    sa.UniqueConstraint('title_video')
    )
    op.create_table('perfil',
    sa.Column('id_perfil', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_perfil', sa.String(length=60), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('label_perfil', sa.String(length=255), nullable=True),
    sa.Column('description_perfil', sa.Text(), nullable=True),
    sa.Column('img_perfil', sa.String(length=255), nullable=True),
    sa.Column('img_portada_perfil', sa.String(length=255), nullable=True),
    sa.Column('id_user_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_user_fk'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id_perfil'),
    sa.UniqueConstraint('id_user_fk'),
    sa.UniqueConstraint('name_perfil')
    )
    op.create_table('grupo',
    sa.Column('id_group', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_group', sa.String(length=60), nullable=False),
    sa.Column('description_group', sa.String(length=255), nullable=False),
    sa.Column('date_creation_group', sa.Date(), nullable=False),
    sa.Column('id_creator_group_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_creator_group_fk'], ['perfil.id_perfil'], ),
    sa.PrimaryKeyConstraint('id_group'),
    sa.UniqueConstraint('name_group')
    )
    op.create_table('miembro_grupo',
    sa.Column('id_perfil_fk', sa.Integer(), nullable=False),
    sa.Column('id_group_fk', sa.Integer(), nullable=False),
    sa.Column('date_register_member', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['id_group_fk'], ['grupo.id_group'], ),
    sa.ForeignKeyConstraint(['id_perfil_fk'], ['perfil.id_perfil'], ),
    sa.PrimaryKeyConstraint('id_perfil_fk', 'id_group_fk')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('miembro_grupo')
    op.drop_table('grupo')
    op.drop_table('perfil')
    op.drop_table('video')
    op.drop_table('users')
    op.drop_table('agente_virtual')
    op.drop_table('admin_main')
    # ### end Alembic commands ###
